### PR TITLE
Implemented thread safe navigation for Android

### PR DESCRIPTION
**Pull request by dmitry-komar**
### Issues Resolved

Given fix provided for situations while navigation operation can be triggered simultaneously.
For example in Halo project crash happens when user closed dialog activity and right after that navigating to another view. It happens because in MainActivity’s OnResume method we call RestoreNavigation, and sometimes RestoreNavigation calls for properties that has been changed by navigation in another thread.

See piece of logs:

> 2022-11-08 19:03:17.558 6200-12784/? V/mono-stdout: LoggingDialogsServiceDecorator: Dialog closed: FlowContainerViewModel
> 2022-11-08 19:03:17.607 6200-6200/? V/mono-stdout: MainActivity: OnResume
> 2022-11-08 19:03:17.614 6200-12378/? V/mono-stdout: HaloDroidFrameNavigationService: Navigated To: OnboardingAlmostReadyViewModel
> 2022-11-08 19:03:17.673 6200-6200/? V/mono-stdout: MainApplication: The app is about to crash. Exception:
> 2022-11-08 19:03:17.674 6200-6200/? V/mono-stdout: MainApplication: System.InvalidOperationException: Stack empty.
> 2022-11-08 19:03:17.674 6200-6200/? V/mono-stdout:   at System.Collections.Generic.Stack1[T].Peek () [0x00016] in <12b37ce1a5e24fcca9a134d6c2495367>:0 
> 2022-11-08 19:03:17.674 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.WhiteLabel.Droid.Internal.BackStack1[T].Current () [0x00000] in <2f86c980f7904c98ab356974749de3e9>:0 
> 2022-11-08 19:03:17.674 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.WhiteLabel.Droid.Navigation.DroidFrameNavigationService+<>c__DisplayClass26_0.<ApplyBackStack>b__0 () [0x00048] in <2f86c980f7904c98ab356974749de3e9>:0 
> 2022-11-08 19:03:17.674 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.Common.Threading.MainThreadExecutorBase.BeginOnUIThread (System.Action action) [0x00008] in <e23bc2ad93a84a0e80e6a9dbd9febcfc>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.Common.Threading.Execute.BeginOnUIThread (System.Action action) [0x00013] in <e23bc2ad93a84a0e80e6a9dbd9febcfc>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.WhiteLabel.Droid.Navigation.DroidFrameNavigationService.ApplyBackStack (Softeq.XToolkit.WhiteLabel.Droid.Internal.BackStack1[T] backStack) [0x00005] in <2f86c980f7904c98ab356974749de3e9>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Softeq.XToolkit.WhiteLabel.Droid.Navigation.DroidFrameNavigationService.RestoreNavigation () [0x00000] in <2f86c980f7904c98ab356974749de3e9>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Halo.Core.Navigation.ApplicationNavigationService.RestoreNavigation () [0x00000] in <661cfc338e0545158ff72f33c31b8ecc>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Halo.Droid.MainActivity.OnResume () [0x0004c] in <285a85feb0c345aea478495ccf7ad699>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <0dfc9de688004b0899f2c465d12db7db>:0 
> 2022-11-08 19:03:17.675 6200-6200/? V/mono-stdout:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <0dfc9de688004b0899f2c465d12db7db>:0 

Added:

 - lock for navigation methods

### Platforms Affected

- Android

### Behavioral/Visual Changes

None

### Before/After Screenshots

Not applicable

### PR Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/Softeq/XToolkit.WhiteLabel/blob/master/.github/CONTRIBUTING.md) document
- [ ] My code follows the [code styles](https://github.com/Softeq/dotnet-guidelines/tree/xamarin_guidelines)
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by wcoder — COMMENTED** [review]
Looks useful, but why are these changes fixing crashes? I mean what problem fixes this PR, could you please add more details/investigation details pieces of stack traces?

**Review by wcoder — CHANGES_REQUESTED** [review]
More details are required for public description.

**Comment by dmitry-komar** [comment]
> Looks useful, but why are these changes fixing crashes? I mean what problem fixes this PR, could you please add more details/investigation details pieces of stack traces?

I've added more details for this fix and also added logs that corresponds to crash that I wanna fix

**Review by dimysa — APPROVED** [review]
LGTM

**Comment by TimofeyBurak** [comment]
@wcoder is there anything else needed for this PR, can you please look?

**Review by wcoder — APPROVED** [review]

**Pull request merged**
